server {
    listen 80; 
    server_name localhost; # Sau này có tên miền bạn sẽ thay ở đây

    location / {
        # Chuyển tiếp yêu cầu đến cổng của Vite
        proxy_pass http://127.0.0.1:5173;
        
        # Các thiết lập quan trọng để hỗ trợ Hot Module Replacement (HMR) của Vite
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}